apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: microsvc
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      initContainers:
        - name: wait-for-deps
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z kafka 29092 && nc -z zookeeper 2181; do
                echo "waiting for kafka and zookeeper";
                sleep 3;
              done
      containers:
        - name: inventory-service
          image: hafsa22/adv_microsvc:inventory-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: microsvc-config
                  key: REDIS_URL_INVENTORY
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: microsvc-config
                  key: KAFKA_BOOTSTRAP
            - name: PYTHONUNBUFFERED
              value: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - inventory-service
                topologyKey: "kubernetes.io/hostname"
