apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-inventory
  namespace: microsvc
spec:
  serviceName: redis-inventory
  replicas: 1
  selector:
    matchLabels:
      app: redis-inventory
  template:
    metadata:
      labels:
        app: redis-inventory
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-inventory-data
              mountPath: /data
            - name: redis-config
              mountPath: /usr/local/etc/redis
      volumes:
        - name: redis-config
          configMap:
            name: microsvc-config
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-inventory-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
