apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: tracing-default
  namespace: microsvc
spec:
  tracing:
    - providers:
        - name: jaeger
      randomSamplingPercentage: 100
