apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - zookeeper/statefulset.yaml
  - zookeeper/service.yaml
  - kafka/statefulset.yaml
  - kafka/service.yaml
  - redis-payment/statefulset.yaml
  - redis-payment/service.yaml
  - redis-inventory/statefulset.yaml
  - redis-inventory/service.yaml
  - redis-order/statefulset.yaml
  - redis-order/service.yaml
  - nginx-ingress.yaml
  - configmap.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml 
  - inventory-service/deployment.yaml
  - inventory-service/service.yaml
  - payment-service/deployment.yaml
  - payment-service/service.yaml
